### ISSUE TITLE
Investigar herramientas de control de flujos por Request

### ISSUE THREAD

**Issue by nanigalli** [nanigalli/on-jobs-publica#12]
Hay que investigar que herramientas existen para manejar el control de flujo por Request y determinar cual vamos a usar.

_Salida recomendada: nuevo apartado en wiki del proyecto_

**Comment by zaragozamartin91** [comment]
Desde la empresa nos informaron que los servidores se encargaran del control de flujo de los requests, de forma tal que el mismo no debe manejarse a nivel código.
